### ISSUE TITLE
Failed attach plugin 'Reunion'

### ISSUE THREAD

**Issue by LcyDev** [s1lentq/reunion#2]
https://paste.gg/p/anonymous/84649e22ed7843b5a61bfd4d72442cad

* rehlds: 3.13.0.788
* regamedll: 5.26.0.668
* metamod: 1.3.0.149
* reunion: 0.2.0.13

**Comment by LcyDev** [comment]
I reinstalled ReHLDS and it worked.

**Comment by rndtrash** [comment]
For those who also encounter this issue: set the `SteamIdHashSalt` value in `reunion.cfg` to any value (I used `no`)🙂
